spring:
  redis:
    host: localhost
    port: 6379
    password: 'whystay'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:mysql://localhost:3306/main_project?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234qwerasdf
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
jwt:
  key: ${JWT_SECRET_KEY}
  refresh-token-expiration-minutes: 420
  access-token-expiration-minutes: 360
mail:
  address:
    admin: admin@gmail.com

#KakaoPay
kakao:
  admin:
    key: 7d8b34bddd92b4d25454fe47608e39ab
  host: http://localhost:8080
